version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7777

    ports:
    - "7777:7777"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

