version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7777
    volumes:
    - .:/code
    ports:
    - "7777:7777"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  db:
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - djangonetwork
volumes:
  postgres_data:

networks:
      djangonetwork:
          driver: bridge
