# Generated by Django 3.2.6 on 2021-08-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'артикль', 'verbose_name_plural': 'артикли'},
        ),
    ]
